### ISSUE TITLE
[conv2d] : Interrupt waiting code hangs sim

### ISSUE THREAD

**Issue by schegde** [hossein1387/BARVINN#22]
Hi!
  I went through the sim for BARVINN (current `master` branch). When I run the sim with the code compiled from `csrc/conv/` , I see that the sim keeps running forever, as you can see here below:
![irq](https://user-images.githubusercontent.com/25887290/189201297-88c1b529-5473-4e6c-9463-413208556ad0.png)

There are few observations from inspecting the APB bus traffic:
1. The APB commands seem to be addressed to all the MVUs. The `mvucommand` register being written to triggers a job with `start[0]`. 
2. But the subsequent `wait_for_mvu_irq()` doesn't seem to complete, and instead somehow seems to reset the processor to execute the code again from start (?) :
![image](https://user-images.githubusercontent.com/25887290/189203808-0d324fa3-7556-4e92-ae99-e215c01a9e96.png)
 
The second group of APB transactions that you see on the right are the exact same `SET_CSR` commands of the conv2d code from beginning, __BUT__ this time with all APB  commands addressed to just one MVU.  Just a zoomed in version of this aspect here: 
![irq_only_one_mvu_cmd](https://user-images.githubusercontent.com/25887290/189205381-38703bf7-bcf2-4da2-a722-ca99634166ff.png)
3. This seems to repeat indefinitely, and every time you hit `wait_for_mvu_irq()` in the first iteration of for loop, it seems to break out of that for loop, and a reset of some sort happens and commands are seen to be issued from beginning.  Is there some other sim setup needed for handling interrupts properly?

---
To confirm its potentially an issue with irq handling, I replaced the `wait_for_mvu_irq()` with just a simple counter in c code  to count up to 50, to provide some delay and have the mvu job completed in the meantime. When I do this, I now see that simulation completes successfully, showing exactly 8 start signals (the `main.c` calls `conv3x3_64` twice, and the `conv3x3_64` function has a for loop running 4 times, each triggering a job). I also see that all APB commands in this scenario are adressed for all 8 MVUs :
![image](https://user-images.githubusercontent.com/25887290/189206898-42255689-685d-473d-a703-92ddf5ab5adc.png)

Do you have any pointers on whats going wrong here with the interrupt handling?

**Comment by hossein1387** [comment]
Hi @schegde thanks for creating the issue.
That is strange. I just want to be able to reproduce your error, could you please clarify on which MVU, pito and BARVINN commit/branch you are? Also, what is the source code you are using?

**Comment by schegde** [comment]
I am still on the same state that I have been working since the last few weeks, with the previous (closed) issues. So I am currently on origin/master <-> https://github.com/hossein1387/BARVINN/commit/3649e73bee82acea44e7f7ffe0d390950af85285 for BARVINN ; origin/master <-> 5e24521b for PITO_RISCV ; and aff7d9d4 for MVU

The C code is from `BARVINN/csrc/conv/src`  at the above revision, with only the following deletions, as recommended by you from previous closed issues:
![image](https://user-images.githubusercontent.com/25887290/189211211-b34e57b0-b23d-4370-b63b-6827e2c084f5.png)

**Comment by schegde** [comment]
Just confirmed https://github.com/obilaniu/MVU/commit/f9e7c487df67e5bcd801da05d30d6a42cdffa4e4 also shows the same sim looping/irq reset issue . However there is one difference that I see with this scenario, compared to the MVU version I described above: In this version , __ALL__ CSR command sets are addressed for all 8 MVUs . As described in https://github.com/hossein1387/BARVINN/issues/22#issue-1366875680  , running with default https://github.com/obilaniu/MVU/commit/aff7d9d40d1ebab67ba9badb6b3dbe96bd7bee40, shows only the first set of  CSR commands addressed for all 8 MVUs, then there is a "reset" and post that remaining all set of CSR commands are addressed for just MVU0

**Comment by hossein1387** [comment]
Thanks for providing the information. I just checked the version in BARVINN's master branch and you are right, it had a bug that was solved in https://github.com/obilaniu/MVU/commit/a1739c2c36bdd6aee988781321e4733052438313 and https://github.com/obilaniu/MVU/commit/8b4965e7e3b10deb157323338e7c3663e001d05b. I just bumped the MVU version to the correct version. Regarding the interrupts, I am not seeing the reset/looping issue that you are reporting. As a reference, for the code you shared above, I ran the simulation, the expected behavior is to get 8 irqs for each hart and then the program should print sth for hart 0 and then exit. Here is the log I am getting:

```

#################################################################################
[ INFO]         0 ns Using /users/hemmat/MyRepos/BARVINN/csrc/conv/build/conv_text.hex as firmware 
[ INFO]         0 ns Using /users/hemmat/MyRepos/BARVINN/csrc/conv/build/conv_data.hex as read only data 
[ INFO]         0 ns Expecting a command line argument  
[ INFO]         0 ns /users/hemmat/MyRepos/BARVINN/csrc/conv/build/conv_text.hex was opened successfully : -19999 
[ INFO]         0 ns /users/hemmat/MyRepos/BARVINN/csrc/conv/build/conv_data.hex was opened successfully : -19998 
[ INFO]         0 ns ======================================================================= 
[ INFO]         0 ns Testbench Setup Phase 
[ INFO]         0 ns ======================================================================= 
[ INFO]         0 ns /users/hemmat/MyRepos/BARVINN/verification/tests/conv/weight.hex was opened successfully : -19996 
[ INFO]   1750.00 ns /users/hemmat/MyRepos/BARVINN/verification/tests/conv/input.hex was opened successfully : -19995 
[ INFO] 206550.00 ns Initializing MVUs... 
[ INFO] 206550.00 ns Initializing RISC-V cores ... 
[ INFO] 206750.00 ns Writing    894 (10.91)% instruction words to the Instruction RAM 
[ INFO] 206750.00 ns Writing     23 (0.28)% instruction words to the Dara RAM 
[ INFO] 206950.00 ns Setup Phase Done ... 
[ INFO] 206950.00 ns Starting Monitor Task 
[ INFO] 206950.00 ns Monitoring the following harts: 
[ INFO] 206950.00 ns 	Hart[0] 
[ INFO] 206950.00 ns Attempt to Sync with DUT hart id 1... 
[ INFO] 206950.00 ns hart id=x 
[ INFO] 207050.00 ns hart id=x 
[ INFO] 207150.00 ns hart id=x 
[ INFO] 207250.00 ns hart id=x 
[ INFO] 207350.00 ns hart id=0 
[ INFO] 207350.00 ns exp=0x00003197: RV32_AUIPC        actual=0x00003197: RV32_AUIPC 
[ INFO] 207350.00 ns Sync with DUT hart id 0 completed... 
[ INFO] 207350.00 ns Monitoring UART ... 
[ INFO] 207350.00 ns Monitoring IRQ ... 
[ INFO] 388850.00 ns monitor::monitor_irq: IRQ received for HART: 0 
[ INFO] 388950.00 ns monitor::monitor_irq: IRQ received for HART: 1 
[ INFO] 389050.00 ns monitor::monitor_irq: IRQ received for HART: 2 
[ INFO] 389150.00 ns monitor::monitor_irq: IRQ received for HART: 3 
[ INFO] 389250.00 ns monitor::monitor_irq: IRQ received for HART: 4 
[ INFO] 389350.00 ns monitor::monitor_irq: IRQ received for HART: 5 
[ INFO] 389450.00 ns monitor::monitor_irq: IRQ received for HART: 6 
[ INFO] 389550.00 ns monitor::monitor_irq: IRQ received for HART: 7 
[ INFO] 472850.00 ns monitor::monitor_irq: IRQ received for HART: 0 
[ INFO] 472950.00 ns monitor::monitor_irq: IRQ received for HART: 1 
[ INFO] 473050.00 ns monitor::monitor_irq: IRQ received for HART: 2 
[ INFO] 473150.00 ns monitor::monitor_irq: IRQ received for HART: 3 
[ INFO] 473250.00 ns monitor::monitor_irq: IRQ received for HART: 4 
[ INFO] 473350.00 ns monitor::monitor_irq: IRQ received for HART: 5 
[ INFO] 473450.00 ns monitor::monitor_irq: IRQ received for HART: 6 
[ INFO] 473550.00 ns monitor::monitor_irq: IRQ received for HART: 7 
[ INFO] 556850.00 ns monitor::monitor_irq: IRQ received for HART: 0 
[ INFO] 556950.00 ns monitor::monitor_irq: IRQ received for HART: 1 
[ INFO] 557050.00 ns monitor::monitor_irq: IRQ received for HART: 2 
[ INFO] 557150.00 ns monitor::monitor_irq: IRQ received for HART: 3 
[ INFO] 557250.00 ns monitor::monitor_irq: IRQ received for HART: 4 
[ INFO] 557350.00 ns monitor::monitor_irq: IRQ received for HART: 5 
[ INFO] 557450.00 ns monitor::monitor_irq: IRQ received for HART: 6 
[ INFO] 557550.00 ns monitor::monitor_irq: IRQ received for HART: 7 
[ INFO] 640850.00 ns monitor::monitor_irq: IRQ received for HART: 0 
[ INFO] 640950.00 ns monitor::monitor_irq: IRQ received for HART: 1 
[ INFO] 641050.00 ns monitor::monitor_irq: IRQ received for HART: 2 
[ INFO] 641150.00 ns monitor::monitor_irq: IRQ received for HART: 3 
[ INFO] 641250.00 ns monitor::monitor_irq: IRQ received for HART: 4 
[ INFO] 641350.00 ns monitor::monitor_irq: IRQ received for HART: 5 
[ INFO] 641450.00 ns monitor::monitor_irq: IRQ received for HART: 6 
[ INFO] 641550.00 ns monitor::monitor_irq: IRQ received for HART: 7 
[ INFO] 840850.00 ns monitor::monitor_irq: IRQ received for HART: 0 
[ INFO] 840950.00 ns monitor::monitor_irq: IRQ received for HART: 1 
[ INFO] 841050.00 ns monitor::monitor_irq: IRQ received for HART: 2 
[ INFO] 841150.00 ns monitor::monitor_irq: IRQ received for HART: 3 
[ INFO] 841250.00 ns monitor::monitor_irq: IRQ received for HART: 4 
[ INFO] 841350.00 ns monitor::monitor_irq: IRQ received for HART: 5 
[ INFO] 841450.00 ns monitor::monitor_irq: IRQ received for HART: 6 
[ INFO] 841550.00 ns monitor::monitor_irq: IRQ received for HART: 7 
[ INFO] 924850.00 ns monitor::monitor_irq: IRQ received for HART: 0 
[ INFO] 924950.00 ns monitor::monitor_irq: IRQ received for HART: 1 
[ INFO] 925050.00 ns monitor::monitor_irq: IRQ received for HART: 2 
[ INFO] 925150.00 ns monitor::monitor_irq: IRQ received for HART: 3 
[ INFO] 925250.00 ns monitor::monitor_irq: IRQ received for HART: 4 
[ INFO] 925350.00 ns monitor::monitor_irq: IRQ received for HART: 5 
[ INFO] 925450.00 ns monitor::monitor_irq: IRQ received for HART: 6 
[ INFO] 925550.00 ns monitor::monitor_irq: IRQ received for HART: 7 
[ INFO] 1008850.00 ns monitor::monitor_irq: IRQ received for HART: 0 
[ INFO] 1008950.00 ns monitor::monitor_irq: IRQ received for HART: 1 
[ INFO] 1009050.00 ns monitor::monitor_irq: IRQ received for HART: 2 
[ INFO] 1009150.00 ns monitor::monitor_irq: IRQ received for HART: 3 
[ INFO] 1009250.00 ns monitor::monitor_irq: IRQ received for HART: 4 
[ INFO] 1009350.00 ns monitor::monitor_irq: IRQ received for HART: 5 
[ INFO] 1009450.00 ns monitor::monitor_irq: IRQ received for HART: 6 
[ INFO] 1009550.00 ns monitor::monitor_irq: IRQ received for HART: 7 
[ INFO] 1092850.00 ns monitor::monitor_irq: IRQ received for HART: 0 
[ INFO] 1092950.00 ns monitor::monitor_irq: IRQ received for HART: 1 
[ INFO] 1093050.00 ns monitor::monitor_irq: IRQ received for HART: 2 
[ INFO] 1093150.00 ns monitor::monitor_irq: IRQ received for HART: 3 
[ INFO] 1093250.00 ns monitor::monitor_irq: IRQ received for HART: 4 
[ INFO] 1093350.00 ns monitor::monitor_irq: IRQ received for HART: 5 
[ INFO] 1093450.00 ns monitor::monitor_irq: IRQ received for HART: 6 
[ INFO] 1093550.00 ns monitor::monitor_irq: IRQ received for HART: 7 
[ INFO] 1206600.00 ns Exception signal was received from HART[0] code name: RV32_EBREAK, 0000002e 
[ INFO] 1206600.00 ns ======================================================================= 
[ INFO] 1206600.00 ns Testbench Report phase 
[ INFO] 1206600.00 ns ======================================================================= 
[ INFO] 1206600.00 ns ======================================================================= 
[ INFO] 1206600.00 ns Test results 
[ INFO] 1206600.00 ns ======================================================================= 
[ INFO] 1206600.00 ns Total Number of tests  = 1456 
[ INFO] 1206600.00 ns Number of passed tests = 1192 
[ INFO] 1206600.00 ns Number of failed tests = 264 
[ INFO] 1206600.00 ns dumping results into result.hex ... 
[ INFO] 1206600.00 ns result.hex was opened successfully : -19993 
[ INFO] 1206600.00 ns => Reading output ram ... 

```
As expected, my programs ends correctly with 8 irqs, here is the waveforms for it:

![Screen Shot 2022-09-08 at 10 31 55 PM](https://user-images.githubusercontent.com/6366236/189260068-31679118-ea12-43a2-9446-2e155c910da4.png)


Putting hart 0 printing at the end aside (since our simple C runtime printf blocks everything on the particular hart until the data transmission on uart is done, meanwhile other harts could reach end of program and consequently, end simulation), I do not see anything wrong. Is there something here that I am missing?

**Comment by hossein1387** [comment]
@schegde can I close the issue or you are still having problem getting correct results?

**Comment by schegde** [comment]
I still see the the hanging/reset issue, and sim hence not ending , with the compiled code files that you sent.  :( . Feel free to close this issue for now, I will investigate further (need some time for this) and report back to you. Thanks for the help!
